import { library } from '@fortawesome/fontawesome-svg-core';

import {
  faArrowRight,
  faBalanceScale,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCreditCardBlank,
  faCode,
  faDatabase,
  faDna,
  faEllipsisV,
  faEllipsisVAlt,
  faFilter,
  faHistory,
  faLevelDown,
  faMindShare,
  faProjectDiagram,
  faRunning,
  faSearch,
  faSignIn,
  faSolarPanel,
  faSpaceShuttle,
  faTools,
  faTruckLoading,
  faUser,
  faUserTie,
} from '@fortawesome/pro-light-svg-icons';

library.add(
  faArrowRight,
  faBalanceScale,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCreditCardBlank,
  faCode,
  faDatabase,
  faDna,
  faEllipsisV,
  faEllipsisVAlt,
  faFilter,
  faHistory,
  faLevelDown,
  faMindShare,
  faProjectDiagram,
  faRunning,
  faSearch,
  faSignIn,
  faSolarPanel,
  faSpaceShuttle,
  faTools,
  faTruckLoading,
  faUser,
  faUserTie,
);