apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-prime
spec:
  selector:
    matchLabels:
      app: fusion-prime
  replicas: 1
  template:
    metadata:
      labels:
        app: fusion-prime
        env: development
    spec:
      containers:
      - name: fusion-prime
        image: gcr.io/fusion-dev-245904/app:v1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: fusion-prime-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: fusion-prime